### ISSUE TITLE
Turn off shadow root

### ISSUE THREAD

**Issue by mnemanja** [WeltN24/create-react-web-component#3]
Hello, 
thanks for this web components implementation. I'm very excited to use it, but I need to know how to turn off the shadow root so that my component can inherit styles?

Thanks!

**Comment by mnemanja** [comment]
Hello @LukasBombach , 
Any update on this will be much appreciated.
Thanks!

**Comment by LukasBombach** [comment]
@mnemanja oh I am sorry, I did not see the issue. Currently, this cannot be done. I can implement this, but I can't promise to do it anytime soon. But I'd appreciate a pull request :)

**Comment by LukasBombach** [comment]
And oh btw, the library for this is https://github.com/WeltN24/react-web-component

**Comment by mnemanja** [comment]
Thanks for responding @LukasBombach ,
I've made a pull request and will appreciate if you can check it out. Thanks ;)
https://github.com/WeltN24/react-web-component/pull/5

**Comment by LukasBombach** [comment]
Awesome! I will look into this after work!
